# Generated by Django 2.2.28 on 2025-06-27 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subsequence_classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsequencelabel',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.KeyFrameAnnotation'),
        ),
    ]
