# Generated by Django 2.2.28 on 2025-09-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0008_auto_20250627_1439'),
        #('annotationweb', '0008_auto_20250228_1420'),
        ('subsequence_classification', '0002_auto_20250627_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='FramePrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_nr', models.IntegerField(default=0)),
                ('filepath', models.TextField(default='')),
                ('predicted_class_info', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ImageSequence')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('sequence', 'frame_nr')},
            },
        ),
    ]
