# Generated by Django 2.2.13 on 2026-05-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotationweb', '0012_auto_20260504_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronchoscopyBoundingBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(max_length=7)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.KeyFrameAnnotation')),
            ],
        ),
    ]
