# Generated by Django 2.2.13 on 2026-02-11 10:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    replaces = [('annotationweb', '0001_initial'), ('annotationweb', '0002_auto_20191118_1104'), ('annotationweb', '0003_keyframeannotation_frame_metadata'), ('annotationweb', '0004_imageannotation_finished'), ('annotationweb', '0005_auto_20201117_1447'), ('annotationweb', '0006_auto_20231124_1525'), ('annotationweb', '0007_auto_20240117_1419'), ('annotationweb', '0008_auto_20250627_1439'), ('annotationweb', '0008_auto_20250228_1420'), ('annotationweb', '0009_merge_20260115_1102'), ('annotationweb', '0010_auto_20260206_1650'), ('annotationweb', '0011_synchronisedtrackingdata'), ('annotationweb', '0012_auto_20260209_1415'), ('annotationweb', '0013_remove_trackingdata_frame_nr'), ('annotationweb', '0014_auto_20260210_1417'), ('annotationweb', '0015_remove_trackingdata_sequence_type'), ('annotationweb', '0016_auto_20260210_1434'), ('annotationweb', '0017_auto_20260210_2057')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color_red', models.PositiveSmallIntegerField(default=255)),
                ('color_green', models.PositiveSmallIntegerField(default=0)),
                ('color_blue', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Label')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Use anonymized id', max_length=200)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Dataset')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('show_entire_sequence', models.BooleanField(default=False, help_text='Allow user to see entire sequence.')),
                ('frames_before', models.PositiveIntegerField(default=0, help_text='How many frames to allow user to see before a key frame')),
                ('frames_after', models.PositiveIntegerField(default=0, help_text='How many frames to allow user to see after a key frame')),
                ('auto_play', models.BooleanField(default=True, help_text='Auto play image sequences')),
                ('shuffle_videos', models.BooleanField(default=True, help_text='Shuffle videos for annotation task')),
                ('user_frame_selection', models.BooleanField(default=False, help_text='Annotaters can select which frames to annotate in a video')),
                ('annotate_single_frame', models.BooleanField(default=True, help_text='Annotate a single frame at a time in videos')),
                ('type', models.CharField(choices=[('classification', 'Classification'), ('blind_classification', 'Blind classification'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('cardiac_plax_segmentation', 'Cardiac PLAX segmentation'), ('cardiac_alax_segmentation', 'Cardiac ALAX segmentation'), ('spline_segmentation', 'Spline segmentation'), ('spline_line_point', 'Splines, lines & point segmentation'), ('image_quality', 'Image Quality'), ('video_annotation', 'Video annotation'), ('subsequence_classification', 'Subsequence classification')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('large_image_layout', models.BooleanField(default=False, help_text='Use a large image layout for annotation')),
                ('dataset', models.ManyToManyField(to='annotationweb.Dataset')),
                ('label', models.ManyToManyField(help_text='<button onclick="window.open(\'/new-label/\', \'Add new label\', \'width=400,height=400,scrollbars=no\');" type="button">Add new label</button>', to='annotationweb.Label')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('post_processing_method', models.CharField(blank=True, default='', help_text='Name of post processing method to use', max_length=255)),
                ('image_quality', models.BooleanField(default=True, help_text='Request image quality evaluation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImageSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text='Should contain # which will be replaced with an integer, increasing with 1 for each frame. E.g. /path/to/frame_#.png', max_length=1024)),
                ('nr_of_frames', models.PositiveIntegerField()),
                ('start_frame_nr', models.PositiveIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=256)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ImageSequence')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image_quality', models.CharField(choices=[('poor', 'Poor'), ('ok', 'OK'), ('good', 'Good'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('comments', models.TextField()),
                ('rejected', models.BooleanField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ImageSequence')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('finished', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyFrameAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_nr', models.PositiveIntegerField()),
                ('image_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.ImageAnnotation')),
                ('frame_metadata', models.CharField(default='', help_text='A text field for storing arbitrary metadata on the current frame', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='VolumetricImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(help_text='Should contain # which will be replaced with an integer, increasing with 1 for each frame. E.g. /path/to/frame_#.png', max_length=1024)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField()),
                ('branch_number', models.PositiveIntegerField()),
                ('position_in_branch', models.FloatField()),
                ('branch_length', models.FloatField()),
                ('branch_generation', models.PositiveIntegerField()),
                ('branch_code', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('offset', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Subject')),
                ('image_sequence', models.ManyToManyField(blank=True, to='annotationweb.ImageSequence')),
            ],
        ),
        migrations.CreateModel(
            name='SynchronisedTrackingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('image_sequence_timestamp', models.FloatField(blank=True, null=True)),
                ('timestamp_difference', models.FloatField(blank=True, null=True)),
                ('tracking_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotationweb.TrackingData')),
                ('tracking_system_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
