# Generated by Django 2.2.13 on 2023-11-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0005_auto_20201117_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('blind_classification', 'Blind classification'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('spline_segmentation', 'Spline segmentation'), ('video_annotation', 'Video annotation')], max_length=50),
        ),
    ]
