# Generated by Django 2.2.13 on 2024-01-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0006_auto_20231124_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('blind_classification', 'Blind classification'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('cardiac_plax_segmentation', 'Cardiac PLAX segmentation'), ('cardiac_alax_segmentation', 'Cardiac ALAX segmentation'), ('spline_segmentation', 'Spline segmentation'), ('video_annotation', 'Video annotation'), ('subsequence_classification', 'Subsequence classification')], max_length=50),
        ),
    ]
