# Generated by Django 2.2.28 on 2025-06-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0007_auto_20240117_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_quality',
            field=models.BooleanField(default=True, help_text='Request image quality evaluation'),
        ),
        migrations.AlterField(
            model_name='imageannotation',
            name='image_quality',
            field=models.CharField(choices=[('poor', 'Poor'), ('ok', 'OK'), ('good', 'Good'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
