# Generated by Django 2.2.28 on 2025-02-28 13:20

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0007_auto_20240117_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumetricImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(
                    help_text='Should contain # which will be replaced with an integer, increasing with 1 for each frame. E.g. /path/to/frame_#.png',
                    max_length=1024)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField()),
                ('branch_number', models.PositiveIntegerField()),
                ('position_in_branch', models.FloatField()),
                ('branch_length', models.FloatField()),
                ('branch_generation', models.PositiveIntegerField()),
                ('branch_code', models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('offset', models.FloatField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotationweb.Subject')),
                ('ultrasound_sequence',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   related_name='ultrasound_sequence', to='annotationweb.ImageSequence')),
                ('video_sequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='video_sequence', to='annotationweb.ImageSequence')),
            ],
        ),
    ]
