# Generated by Django 2.2.13 on 2026-01-15 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0008_auto_20250228_1420'),
        ('annotationweb', '0008_auto_20250627_1439'),
    ]

    operations = [
    ]
