# Generated by Django 2.2.13 on 2026-02-11 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0009_merge_20260115_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('blind_classification', 'Blind classification'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('cardiac_plax_segmentation', 'Cardiac PLAX segmentation'), ('cardiac_alax_segmentation', 'Cardiac ALAX segmentation'), ('spline_segmentation', 'Spline segmentation'), ('spline_line_point', 'Splines, lines & point segmentation'), ('image_quality', 'Image Quality'), ('video_annotation', 'Video annotation'), ('subsequence_classification', 'Subsequence classification')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='trackingdata',
            name='ultrasound_sequence',
        ),
        migrations.RemoveField(
            model_name='trackingdata',
            name='video_sequence',
        ),
        migrations.AddField(
            model_name='trackingdata',
            name='image_sequence',
            field=models.ManyToManyField(blank=True, to='annotationweb.ImageSequence'),
        ),
        migrations.CreateModel(
            name='SynchronisedTrackingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('image_sequence_timestamp', models.FloatField(blank=True, null=True)),
                ('timestamp_difference', models.FloatField(blank=True, null=True)),
                ('tracking_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotationweb.TrackingData')),
                ('tracking_system_timestamp', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
