# Generated by Django 2.2.13 on 2026-07-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotationweb', '0010_subsequence_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synchronisedtrackingdata',
            name='timestamp_difference',
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('classification', 'Classification'), ('blind_classification', 'Blind classification'), ('boundingbox', 'Bounding box'), ('landmark', 'Landmark'), ('cardiac_segmentation', 'Cardiac segmentation'), ('cardiac_plax_segmentation', 'Cardiac PLAX segmentation'), ('cardiac_alax_segmentation', 'Cardiac ALAX segmentation'), ('spline_segmentation', 'Spline segmentation'), ('spline_line_point', 'Splines, lines & point segmentation'), ('image_quality', 'Image Quality'), ('video_annotation', 'Video annotation'), ('subsequence_classification', 'Subsequence classification'), ('bronchoscopy_bounding_box', 'Bronchoscopy bounding box')], max_length=50),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='branch_generation',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='branch_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='branch_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='position_in_branch',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='timestamp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
